# ================================
# CONFIGURACIÓN GENERAL DEL SERVIDOR
# ================================
server:
  port: 8083
  servlet:
    context-path: /api

# ================================
# CONFIGURACIÓN DE CLIENTES HTTP (WebClient)
# ================================
cliente:
  servicio:
    base-url: https://api.externoservicio.com
    timeout: 5000

# ================================
# CONFIGURACIÓN DE BASE DE DATOS (si aplica)
# ================================
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mi_basedatos
    username: usuario
    password: contraseña
  sql:
    init:
      mode: always